# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='uid',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
