# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='uid',
        ),
    ]
