# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_todo_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.CharField(default='defaultname', max_length=40),
        ),
    ]
